# Generated by Django 5.0.6 on 2024-06-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookedon',
            new_name='booked_on',
        ),
    ]
